update ssh wrapper script for new hosts with local user

diff --git a/bin/ssh_init b/bin/ssh_init
--- a/bin/ssh_init
+++ b/bin/ssh_init
@@ -1,7 +1,15 @@
 #!/bin/bash
-# Very simple script to wrap ssh and push some essential dotfiles / pubkey to remote hosts on first connect.
+# Not so script to wrap ssh and push some essential dotfiles / pubkey to remote hosts on first connect.
+# Config LOCAL_USERNAME with your local account username
+LOCAL_USERNAME=""
+# config FQDN with your search path, e.g. ".company.com"
+FQDN=""
 CONNECT=$1
 EXIT_CODE=0
+FIRST_CONNECT=0
+KNOWN_HOST=1
+LOCAL_USER=1
+DOMAIN=1
 
 update_dotfiles() {
     local EXIT=0
@@ -24,19 +32,44 @@ update_dotfiles() {
 if [[ $CONNECT == *@* ]]; then
   # Note: this assumes the variable (first argument) has no spaces
   arr=(${CONNECT//@/ })
-  USER=${arr[0]}
+  SSH_USER=${arr[0]}
   REMOTE_HOST=${arr[1]}
 else
   REMOTE_HOST=$CONNECT
 fi
 
-# Check .ssh/known-hosts. If ! exists, ssh initially to connect and make homedir. If not, skip sttep 2 and just connect
-if ! grep -i "$REMOTE_HOST" ~/.ssh/known_hosts &>/dev/null ; then
+# check .ssh/known-hosts for the host specified. This has to be checked early, but will
+# be used later
+if grep -i "$REMOTE_HOST" ~/.ssh/known_hosts &>/dev/null ; then
+    KNOWN_HOST=0
+fi
 
+# check for local user access. new servers only, cent 7 +
+if ssh -T -o PasswordAuthentication=no ${LOCAL_USERNAME}@${REMOTE_HOST} "exit" 2>/dev/null; then
+    LOCAL_USER=0
+fi
+
+# check for an domain connected machine
+if [[ LOCAL_USER -ne 0 ]] && ! [[ $REMOTE_HOST == *fisdap* ]] && ! [[ $REMOTE_HOST == *medhub* ]]; then
+    DOMAIN=0
+    REMOTE_HOST=${REMOTE_HOST}${FQDN}
+    CONNECT=${CONNECT}${FQDN}
+    # if we can successfully auth with our key, this is not our first connect
+    if ssh -T -o PasswordAuthentication=no ${REMOTE_HOST} "exit" 2>/dev/null; then
+        FIRST_CONNECT=1
+    fi
+else
+    # if our host is not on the domain, check .ssh/known-hosts for the host specified
+    if [[ KNOWN_HOST -eq 0 ]]; then
+        FIRST_CONNECT=1
+    fi
+fi
+
+if [[ FIRST_CONNECT -eq 0 ]]; then
     # If we have a defined user and that user is root
-    if [ ! -z $USER ] && [ "$USER" = "root" ]; then 
+    if [ ! -z $SSH_USER ] && [ "$SSH_USER" = "root" ]; then 
         # Just connect, don't try to futz with the environment
-        ssh -t $@ "$(< ~/bin/quickcheck); bash --login" || EXIT_CODE=2
+        ssh -t $CONNECT "$(< ~/bin/quickcheck); bash --login" || EXIT_CODE=2
         # Remove our host from the known hosts list after connecting
         sed -i "/${REMOTE_HOST}/d" ~/.ssh/known_hosts
         exit $EXIT_CODE
@@ -44,11 +77,19 @@ if ! grep -i "$REMOTE_HOST" ~/.ssh/known_hosts &>/dev/null ; then
     elif [[ $REMOTE_HOST == *"medhub"* ]]; then
         :
     else
-        if ssh-copy-id -i ~/.ssh/id_rsa.pub $CONNECT; then
+        # test if this is a new host with the local account 
+        if [[ LOCAL_USER -eq 0 ]]; then
+            echo "Copying essential dotfiles"
+            if ! update_dotfiles; then
+                echo "WARNING: Unable to rsync files"
+            fi
+
+        # Legacy connections to domain joined machines
+        elif ssh-copy-id -i ~/.ssh/id_rsa.pub $CONNECT; then
             echo "Ensuring .ssh context"
-            # we must include an "or exit 0" in our cmd so that the absense of the redhat-release file doesn't 
-            # end our script prematurely
-            /bin/ssh -t -t $@ '[[ -e /etc/redhat-release ]] && sudo chcon -R -t ssh_home_t ~/.ssh || exit 0' || exit 5
+            # we must include an "or exit 0" in our cmd so that the absense of the 
+            # redhat-release file doesn't end our script prematurely
+            /bin/ssh -t -t $CONNECT '[[ -e /etc/redhat-release ]] && grep "release 6" /etc/redhat-release >/dev/null && sudo chcon -R -t ssh_home_t ~/.ssh || exit 0' || exit 5
 
             echo "Copying essential dotfiles"
             if ! update_dotfiles; then
@@ -63,4 +104,10 @@ if ! grep -i "$REMOTE_HOST" ~/.ssh/known_hosts &>/dev/null ; then
 fi
 
 # Lastly connect
-ssh -t $@ "$(< ~/bin/quickcheck); bash --login"
+if [[ LOCAL_USER -eq 0 ]]; then
+    ssh -t -o passwordauthentication=no ${LOCAL_USERNAME}@${REMOTE_HOST} "$(< ~/bin/quickcheck); bash --login"
+elif ! [ -z $SSH_USER ]; then 
+    ssh -t ${SSH_USER}@${REMOTE_HOST} "$(< ~/bin/quickcheck); bash --login"
+else
+    ssh -t ${REMOTE_HOST} "$(< ~/bin/quickcheck); bash --login"
+fi
